import { SettingsField } from './SettingsPanel';

export type ContentType = 'docs' | 'blog' | 'page' | 'unknown';

export interface ExistingValues {
  [key: string]: string | undefined;
}

export function getDocFrontmatterFields(existing: ExistingValues, defaultTitle: string): SettingsField[] {
  const val = (k: string, def?: string) => existing[k] ?? def;
  return [
    { name: 'id', type: 'text', label: 'id', description: 'A unique document ID.', placeholder: 'Type: string, Default: file path (including folders, without the extension)', currentValue: val('id') },
    { name: 'title', type: 'text', label: 'title', description: 'The text title of your document. Used for the page metadata and as a fallback value in multiple places (sidebar, next/previous buttons...). Automatically added at the top of your doc if it does not contain any Markdown title.', placeholder: 'Type: string, Default: Markdown title or id', currentValue: val('title', defaultTitle) },

    { name: 'pagination_label', type: 'text', label: 'pagination_label', description: 'The text used in the document next/previous buttons for this document.', placeholder: 'Type: string, Default: sidebar_label or title', currentValue: val('pagination_label') },
    { name: 'sidebar_label', type: 'text', label: 'sidebar_label', description: 'The text shown in the document sidebar for this document.', placeholder: 'Type: string, Default: title', currentValue: val('sidebar_label') },
    { name: 'sidebar_position', type: 'number', label: 'sidebar_position', description: 'Controls the position of a doc inside the generated sidebar slice when using autogenerated sidebar items. See also <a href="https://docusaurus.io/docs/sidebar/autogenerated#autogenerated-sidebar-metadata">Autogenerated sidebar metadata</a>.', placeholder: 'Type: number, Default: Default ordering', currentValue: val('sidebar_position') },
    { name: 'sidebar_class_name', type: 'text', label: 'sidebar_class_name', description: 'Gives the corresponding sidebar label a special class name when using autogenerated sidebars.', placeholder: 'Type: string, Default: undefined', currentValue: val('sidebar_class_name') },
    { name: 'sidebar_key', type: 'text', label: 'sidebar_key', description: 'Gives the corresponding sidebar item a key to uniquely identify the sidebar item. This is mostly useful for i18n sites to generate unique translation keys for categories sharing the same labels. An error will tell you when this extra metadata is needed.', placeholder: 'Type: string, Default: undefined', currentValue: val('sidebar_key') },
    { name: 'sidebar_custom_props', type: 'text', label: 'sidebar_custom_props', description: 'Assign <a href="https://docusaurus.io/docs/sidebar#passing-custom-props">custom props</a> to the sidebar item referencing this doc', placeholder: 'Type: object, Default: undefined', currentValue: val('sidebar_custom_props') },
    { name: 'displayed_sidebar', type: 'text', label: 'displayed_sidebar', description: 'Force the display of a given sidebar when browsing the current document. Read the <a href="https://docusaurus.io/docs/sidebar/multiple-sidebars">multiple sidebars guide</a> for details.', placeholder: 'Type: string, Default: undefined', currentValue: val('displayed_sidebar') },

    { name: 'hide_title', type: 'boolean', label: 'hide_title', description: 'Whether to hide the title at the top of the doc. It only hides a title declared through the front matter, and have no effect on a Markdown title at the top of your document.', currentValue: val('hide_title'), defaultValue: 'false' },
    { name: 'hide_table_of_contents', type: 'boolean', label: 'hide_table_of_contents', description: 'Whether to hide the table of contents to the right.', currentValue: val('hide_table_of_contents'), defaultValue: 'false' },
    { name: 'toc_min_heading_level', type: 'number', label: 'toc_min_heading_level', description: 'The minimum heading level shown in the table of contents. Must be between 2 and 6 and lower or equal to the max value.', placeholder: 'Type: number, Default: 2', currentValue: val('toc_min_heading_level'), defaultValue: '2' },
    { name: 'toc_max_heading_level', type: 'number', label: 'toc_max_heading_level', description: 'The max heading level shown in the table of contents. Must be between 2 and 6.', placeholder: 'Type: number, Default: 3', currentValue: val('toc_max_heading_level'), defaultValue: '3' },

    { name: 'pagination_prev', type: 'text', label: 'pagination_prev', description: 'The ID of the documentation you want the "Previous" pagination to link to. Use null to disable showing "Previous" for this page.', placeholder: 'Type: string|null, Default: Previous doc in the sidebar', currentValue: val('pagination_prev') },
    { name: 'pagination_next', type: 'text', label: 'pagination_next', description: 'The ID of the documentation you want the "Next" pagination to link to. Use null to disable showing "Next" for this page.', placeholder: 'Type: string|null, Default: Next doc in the sidebar', currentValue: val('pagination_next') },

    { name: 'parse_number_prefixes', type: 'boolean', label: 'parse_number_prefixes', description: 'Whether number prefix parsing is disabled on this doc. See also <a href="https://docusaurus.io/docs/sidebar/autogenerated#using-number-prefixes">Using number prefixes</a>.', currentValue: val('parse_number_prefixes') },
    { name: 'custom_edit_url', type: 'text', label: 'custom_edit_url', description: 'The URL for editing this document. Use null to disable showing "Edit this page" for this page.', placeholder: 'Type: string|null, Default: Computed using editUrl plugin option', currentValue: val('custom_edit_url') },

    { name: 'keywords', type: 'text', label: 'keywords', description: 'Keywords meta tag for the document page, for search engines.', placeholder: 'Example: [keywords, describing, the main topics], Type: string[], Default: undefined', currentValue: val('keywords') },
    { name: 'description', type: 'text', label: 'description', description: 'The description of your document, which will become the <meta name="description" content="..."/> and <meta property="og:description" content="..."/> in <head>, used by search engines.', placeholder: 'Type: string, Default: First line of Markdown content', currentValue: val('description') },
    { name: 'image', type: 'text', label: 'image', description: 'Cover or thumbnail image that will be used as the <meta property="og:image" content="..."/> in the <head>, enhancing link previews on social media and messaging platforms.', placeholder: 'Type: string, Default: undefined', currentValue: val('image') },
    { name: 'slug', type: 'text', label: 'slug', description: 'Allows to customize the document URL (/<routeBasePath>/<slug>). Support multiple patterns: slug: my-doc, slug: /my/path/myDoc, slug: /.', placeholder: 'Type: string, Default: File path', currentValue: val('slug') },
    { name: 'tags', type: 'text', label: 'tags', description: 'A list of strings or objects of two string fields label and permalink to tag to your docs. Strings can be a reference to keys of a <a href="https://docusaurus.io/docs/api/plugins/@docusaurus/plugin-content-docs#tags-file">tags file</a> (usually tags.yml)', placeholder: 'Example: [releases, announcements, emptyTag], Type: Tag[], Default: undefined', currentValue: val('tags') },

    { name: 'draft', type: 'boolean', label: 'draft', description: 'Draft documents will only be available during development.', currentValue: val('draft'), defaultValue: 'false' },
    { name: 'unlisted', type: 'boolean', label: 'unlisted', description: 'Unlisted documents will be available in both development and production. They will be "hidden" in production, not indexed, excluded from sitemaps, and can only be accessed by users having a direct link.', currentValue: val('unlisted'), defaultValue: 'false' },

    // Optional advanced field (as raw YAML line)
    { name: 'last_update', type: 'text', label: 'last_update', description: 'Allows overriding the last update author/date. Date can be any <a href="https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date/parse">parsable date string</a>.', placeholder: 'Example:  \{ date: \'2000-01-01\', author: \'custom author name\' \},Type: {date?: string; author?: string}, Default: undefined', currentValue: val('last_update') },
  ];
}

export function getFieldsForContentType(type: ContentType, existing: ExistingValues, defaultTitle: string): SettingsField[] {
  if (type === 'docs') return getDocFrontmatterFields(existing, defaultTitle);
  // Placeholders to reserve logic for blog & pages
  if (type === 'blog') {
    return [
      { name: 'title', type: 'text', label: 'Title', currentValue: existing['title'] ?? defaultTitle },
      { name: 'slug', type: 'text', label: 'Slug', currentValue: existing['slug'] },
      { name: 'tags', type: 'text', label: 'Tags', currentValue: existing['tags'] },
      { name: 'draft', type: 'boolean', label: 'Draft', currentValue: existing['draft'] },
    ];
  }
  if (type === 'page') {
    return [
      { name: 'title', type: 'text', label: 'Title', currentValue: existing['title'] ?? defaultTitle },
      { name: 'description', type: 'text', label: 'Description', currentValue: existing['description'] },
      { name: 'slug', type: 'text', label: 'Slug', currentValue: existing['slug'] },
    ];
  }
  return [];
}

export function groupFields(type: ContentType, fields: SettingsField[]): { [group: string]: SettingsField[] } {
  if (type !== 'docs') {
    return { 'Basic': fields };
  }
  const byName: Record<string, SettingsField | undefined> = {};
  for (const f of fields) byName[f.name] = f;
  const pick = (names: string[]) => names.map(n => byName[n]).filter(Boolean) as SettingsField[];
  return {
    'Identity & URL': pick(['id', 'title', 'slug', 'image', 'keywords', 'description', 'tags']),
    'Sidebar': pick(['sidebar_label', 'sidebar_position', 'sidebar_class_name', 'sidebar_key', 'sidebar_custom_props', 'displayed_sidebar']),
    'TOC & Visibility': pick(['hide_title', 'hide_table_of_contents', 'toc_min_heading_level', 'toc_max_heading_level']),
    'Pagination': pick(['pagination_label', 'pagination_prev', 'pagination_next']),
    'Editing & Source': pick(['custom_edit_url', 'parse_number_prefixes']),
    'Drafting': pick(['draft', 'unlisted']),
    'Advanced': pick(['last_update'])
  };
}

